version: '3'

services:
  docker-nginx-reload:
    image: docker-nginx-reload
    build: .
    ports:
      - "8000:8000"
    restart: on-failure
    environment:
      VAULT_API_URL: "https://pki.mainflux.cloud"
      VAULT_CA_INTERMEDIATE: "true"
      VAULT_SECRET_ROOT: "pki"
      VAULT_SECRET_INTERMEDIATE: "pki_int"
      CRL_FILE_PATH: "crl.pem"
      CMD_TO_EXEC: ".*nginx: master.*"
      API_PORT: "8000"
      API_ENDPOINT: "/reload"
    volumes:
      -  ${PWD}/crl.pem:/crl.pem
